# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
# [combine-prs-workflow](https://github.com/hrvey/combine-prs-workflow)

version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "murielmay67"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    assignees:
        - "murielmay67"
    directory: "/"
    schedule:
      interval: "daily"
