# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# [combine-prs-workflow](https://github.com/hrvey/combine-prs-workflow)

# [renovate](https://github.com/renovatebot/renovate)

version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "murielmay67"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    assignees:
      - "murielmay67"
    directory: "/docker"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/vite-vue-ts"
    assignees:
      - "murielmay67"
    schedule:
      interval: "daily"
    groups: # https://mglaman.dev/blog/my-dependabot-configuration-drupal-and-other-php-projects
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "npm"
    directory: "/vite-react-ts"
    groups:
      production-dependencies:
        dependency-type: "production"
        update-types:
          # https://semver.org/lang/zh-CN/
          # - "major"
          - "minor"
          - "patch"
      development-dependencies:
        dependency-type: "development"
    assignees:
      - "murielmay67"
    schedule:
      interval: "daily"
