kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: alpine
    image: alpine
    commands:
      - pwd
      - ls -l
      - ls -l /drone
      - uname -a

  - name: env
    image: alpine
    commands:
      - env

    # https://developer.harness.io/docs/continuous-integration/use-ci/use-drone-plugins/drone-email-plugin/
    # https://plugins.drone.cool/plugins/email
    # https://plugins.drone.io/plugins/email
    # https://github.com/drillster/drone-email
    # https://github.com/Famine-Life/drone-email-defaults-ZN
  - name: notify
    image: yanhao98/drone-email:arm
    # image: drillster/drone-email
    settings:
      host: smtp.qiye.aliyun.com
      port: 465
      username: notifications@yanhao.ren
      password: 7u57E3JQZz9W7HE2
      from: Drone CI <notifications@yanhao.ren>
      recipients_only: true
      recipients: xx2@19980901.xyz
      # recipients_file
      # subject: 'Drone Build {{ build.number }} for {{ repo.name }}'
      # body: 'build {{ build.number }} for {{ repo.name }} {{ build.status }}'
      # attachment:
      #   - /drone/src/someFile.txt
      attachments:
        - /drone/src/someFile.txt
        - /drone/src/someFile.html
    # when:
    #   status:
    #     - success
    #     - changed
    #     - failure
