kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: alpine
    image: alpine
    commands:
      - pwd
      - ls -l
      - ls -l /drone
      - uname -a

  - name: env
    image: alpine
    commands:
      - env

    # https://developer.harness.io/docs/continuous-integration/use-ci/use-drone-plugins/drone-email-plugin/
    # https://plugins.drone.cool/plugins/email
    # https://plugins.drone.io/plugins/email
  - name: sendmail
    image: drillster/drone-email
    settings:
      host: smtp.some-server.com
      username: foo
      password: bar
      from: drone@your-domain.com
    when:
      status:
        - failure
        - success
