kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: pwd
    image: alpine
    commands:
      - pwd
      - ls -l
      - ls -l /drone
      - env
      - uname -a
