kind: pipeline
type: docker
name: default-1
platform:
  os: linux
  arch: arm64
steps:
  - name: default-1
    image: alpine
    commands:
      - apk add curl
      - curl ip.sb
      - pwd
      - ls -l
      - touch /drone/src/created-by-drone-0.txt
      - ls -l
      - date

  - name: default-2
    image: alpine
    commands:
      - apk add curl
      - curl ip.sb
      - pwd
      - ls -l
      - date

--- # volumes
kind: pipeline
type: docker
name: volume-test
clone:
  disable: true
platform:
  os: linux
  arch: arm64
steps:
  - name: volume-test-1
    image: alpine
    volumes:
      - name: files
        path: /files
    commands:
      - pwd
      - touch ./created-by-drone-1.txt
      - ls -l
      - touch /files/created-by-drone-2.txt
  - name: volume-test-2
    image: alpine
    volumes:
      - name: files
        path: /files
    commands:
      - pwd
      - ls -l
      - ls -l /files
# https://docs.drone.io/pipeline/kubernetes/syntax/volumes/temporary/
volumes:
  - name: files
    temp: {}

--- # 邮件通知
kind: pipeline
type: docker
name: notify
platform:
  os: linux
  arch: arm64
steps:
  - name: notify
    image: yanhao98/drone-email
    settings:
      from.name: Drone CI
      from.address: notifications@yanhao.ren
      host: smtp.qiye.aliyun.com
      port: 465
      username: notifications@yanhao.ren
      password:
        from_secret: email_password
      recipients_only: true
      recipients: drone-build-notify@19980901.xyz
      attachments:
        - /drone/src/someFile.txt
        - /drone/src/someFile.html
    when:
      status:
        - failure
        - success
depends_on:
  - default-1

--- # docker
kind: pipeline
type: docker
name: docker
# drone exec --pipeline docker --trusted --secret-file=.drone.sec
platform:
  os: linux
  arch: arm64
steps:
  - name: Docker build
    # image: docker
    image: docker:dind
    # https://github.com/drone-plugins/drone-docker
    # https://docs.drone.io/pipeline/docker/examples/services/docker/
    # https://docs.drone.io/pipeline/docker/examples/services/docker_dind/
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - trap 'docker logout' EXIT
      - echo $DOCKER_PASSWORD | docker login -u yanhao98 --password-stdin
      - docker buildx create --name drone --bootstrap
      - docker buildx build . --platform linux/amd64,linux/arm64 -t yanhao98/drone-test-image:latest --push --builder drone;
      - echo "End of build"
volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
