kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: alpine
    image: alpine
    commands:
      - pwd
      - ls -l
      - ls -l /drone
      - uname -a

  - name: env
    image: alpine
    commands:
      - env

    # https://developer.harness.io/docs/continuous-integration/use-ci/use-drone-plugins/drone-email-plugin/
    # https://plugins.drone.cool/plugins/email
  - name: sendmail
    image: drillster/drone-email
    settings:
      host: smtp.qiye.aliyun.com
      username: notifications@yanhao.ren
      password: 7u57E3JQZz9W7HE2
      port: 465
      skip_verify: true
      from: notifications@yanhao.ren
      recipients: me@yanhao.ren
      subject: Drone
      body: xxx
