kind: pipeline
type: docker
name: default

# platform:
#   os: linux
#   arch: arm64

steps:
  - name: alpine
    image: alpine
    commands:
      - pwd
      - ls -l
      - ls -l /drone
      - uname -a

  - name: env
    image: alpine
    commands:
      - env

    # https://developer.harness.io/docs/continuous-integration/use-ci/use-drone-plugins/drone-email-plugin/
    # https://plugins.drone.cool/plugins/email
    # https://plugins.drone.io/plugins/email
  - name: notify
    image: drillster/drone-email
    settings:
      host: smtp.qiye.aliyun.com
      port: 465
      username: notifications@yanhao.ren
      password: 7u57E3JQZz9W7HE2
      from: Drone CI <notifications@yanhao.ren>
      recipients_only: true
      recipients: xx2@19980901.xyz
      # recipients_file
      subject: 'Drone Build {{ build.number }} for {{ repo.name }}'
      # body: |
      #   {{#success build.status}}
      #     Build {{ build.number }} succeeded for {{ repo.name }}
      #   {{else}}
      #     Build {{ build.number }} failed for {{ repo.name }}
      #   {{/success}}
      # body: file:///drone/src/someFile.txt
      body: |
        The File Content is: /drone/src/someFile.txt
      attachment:
        - /drone/src/someFile.txt
    when:
      status:
        - success
        - changed
        - failure
