kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: alpine
    image: alpine
    commands:
      - pwd
      - ls -l
      - ls -l /drone
      - uname -a

  - name: env
    image: alpine
    commands:
      - env

  - name: sendmail
    image: drillster/drone-email
    settings:
      host: smtp.qiye.aliyun.com
      port: 465
      skip_verify: true
      username: notifications@yanhao.ren
      password: 7u57E3JQZz9W7HE2
      from: notifications@yanhao.ren
      recipients: [me@yanhao.ren, sb@19980901.xyz]
      subject: 'Drone CI'
      body: |
        {{#success build.status}}
          Build {{build.number}} succeeded.
        {{else}}
          Build {{build.number}} failed.
        {{/success}}
        {{#build.commit}}
          Commit {{build.commit}} by {{build.author}}.
        {{/build.commit}}
        {{#build.branch}}
          Branch {{build.branch}}.
        {{/build.branch}}
        {{#build.link}}
          <a href="{{build.link}}">View on Drone</a>.
        {{/build.link}}
