kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
  - name: alpine
    image: alpine
    commands:
      - pwd
      - ls -l
      - ls -l /drone
      - uname -a
      - touch /drone/src/created-by-drone.txt
      - ls -l
      - apk add curl
      - curl ip.sb

---
kind: pipeline
type: docker
name: alpine-1
platform:
  os: linux
  arch: arm64
steps:
  - name: alpine
    image: alpine
    commands:
      - apk add curl
      - curl ip.sb

---
kind: pipeline
type: docker
name: alpine-2
platform:
  os: linux
  arch: arm64
steps:
  - name: alpine
    image: alpine
    commands:
      - apk add curl
      - curl ip.sb

---
kind: pipeline
type: docker
name: env
platform:
  os: linux
  arch: arm64
steps:
  - name: env
    image: alpine
    commands:
      - env

---
kind: pipeline
type: docker
name: notify
platform:
  os: linux
  arch: arm64
steps:
  - name: notify
    image: yanhao98/drone-email
    settings:
      from.name: Drone CI
      from.address: notifications@yanhao.ren
      host: smtp.qiye.aliyun.com
      port: 465
      username: notifications@yanhao.ren
      password:
        from_secret: email_password
      recipients_only: true
      recipients: xx2@19980901.xyz
      attachments:
        - /drone/src/someFile.txt
        - /drone/src/someFile.html
depends_on:
  - default
  - env
