kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
  - name: default-1
    image: alpine
    commands:
      - apk add curl
      - curl ip.sb
      - pwd
      - ls -l
      - touch /drone/src/created-by-drone-0.txt
      - ls -l
      - date

  - name: default-2
    image: alpine
    commands:
      - apk add curl
      - curl ip.sb
      - pwd
      - ls -l
      - date

--- # volumes
kind: pipeline
type: docker
name: volume-test
clone:
  disable: true
platform:
  os: linux
  arch: arm64
steps:
  - name: volume-test-1
    image: alpine
    volumes:
      - name: files
        path: /files
    commands:
      - pwd
      - touch ./created-by-drone-1.txt
      - ls -l
      - touch /files/created-by-drone-2.txt
  - name: volume-test-2
    image: alpine
    volumes:
      - name: files
        path: /files
    commands:
      - pwd
      - ls -l
      - ls -l /files
# https://docs.drone.io/pipeline/kubernetes/syntax/volumes/temporary/
volumes:
  - name: files
    temp: {}

--- # 邮件通知
kind: pipeline
type: docker
name: notify
platform:
  os: linux
  arch: arm64
steps:
  - name: notify
    image: yanhao98/drone-email
    settings:
      from.name: Drone CI
      from.address: notifications@yanhao.ren
      host: smtp.qiye.aliyun.com
      port: 465
      username: notifications@yanhao.ren
      password:
        from_secret: email_password
      recipients_only: true
      recipients: xx2@19980901.xyz
      attachments:
        - /drone/src/someFile.txt
        - /drone/src/someFile.html
depends_on:
  - default
