kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: arm64
steps:
  - name: default-1
    image: alpine
    volumes:
      - name: cache
        path: /drone/src
    commands:
      - apk add curl
      - curl ip.sb
      - pwd
      - ls -l
      - touch /drone/src/created-by-drone.txt
      - ls -l
      - date
  - name: default-2
    image: alpine
    volumes:
      - name: cache
        path: /drone/src
    commands:
      - apk add curl
      - curl ip.sb
      - pwd
      - ls -l
      - date
volumes:
  - name: cache
    temp: {}

--- # 邮件通知
kind: pipeline
type: docker
name: notify
clone:
  disable: true
platform:
  os: linux
  arch: arm64
steps:
  - name: notify
    image: yanhao98/drone-email
    settings:
      from.name: Drone CI
      from.address: notifications@yanhao.ren
      host: smtp.qiye.aliyun.com
      port: 465
      username: notifications@yanhao.ren
      password:
        from_secret: email_password
      recipients_only: true
      recipients: xx2@19980901.xyz
      attachments:
        - /drone/src/someFile.txt
        - /drone/src/someFile.html
depends_on:
  - default
