# docker compose up --build
version: '3'
services:
  debug:
    container_name: debug
    environment:
      - FOO=bar
    build: 
      # context: .
      pull: true
    init: true
    # tty: true
    stdin_open: true
