name: Setup Node Test

on:
  push:
  #   branches: ["main"]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:
  Test-Setup-Node:
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04
    container:
      image: catthehacker/ubuntu:act-latest
      # 方法二，手动指定持久化目录
      # volumes:
      #   - ubuntu_hostedtoolcache:/opt/hostedtoolcache
    env:
      RUNNER_TOOL_CACHE: /toolcache
    steps:
      - run: echo "node version $(node -v)"

      - uses: actions/checkout@v4

      - run: ls -al

      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true

      # 0052 这次提交恢复缓存和上次对比。
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: "./vite-project/pnpm-lock.yaml"

      - run: echo "node version $(node -v)"
