name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀

on:
  push:
    branches: ["main"]
    paths:
      - "vite-vue-ts/**"
      - ".gitea/workflows/010-demo.yaml"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Explore-Job:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-arm64, ubuntu-amd64]
    steps:
      - name: script
        run: |
          time $(i=0; while (( i < 999992 )); do (( i ++ )); done);
          set -x
          echo "🕒 date: $(date)"
          curl -s ip.sb
          env | sort
          node -v
          echo $0
          ps -p $$
          echo $SHELL
          echo ${{ vars.SOME_VAR }}
          echo $SOME_VAR
          echo "${{ github.actor }} is testing out Gitea Actions 🚀"
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
          ls ${{ github.workspace }}
          echo "🍏 This job's status is ${{ job.status }}."
      - run: echo "🍏 This job's status is ${{ job.status }}."

  sparse-checkout:
    runs-on: ubuntu-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /vite-vue-ts/
          sparse-checkout-cone-mode: false
      - run: ls -al
      - run: ls -al vite-vue-ts
