name: Sync to GitHub

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-github:
    runs-on: ubuntu-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to GitHub # https://github.com/murielmay67/ci-demo
        run: |
          git remote set-url origin https://${{ secrets.GH_TOKEN_MURIELMAY67 }}@github.com/murielmay67/ci-demo.git
          git push origin main --force
