# [2 Ways to Use Your Own Docker Image in Github Actions](https://yonatankra.com/2-ways-to-use-your-docker-image-in-github-actions/)
# https://github.com/g-plane/pnpm-docker
# https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time

# act --workflows .gitea/workflows/41-pnpm.yml --pull=false

on:
  push:
    branches: ["main"]
    paths:
      - "vite-vue-ts/**"
      - "vite-react-ts/**"
      - ".gitea/workflows/041-pnpm.yml"
# defaults:
#   run:
#     shell: bash
jobs:
  pnpm:
    # runs-on: pnpm-node20-arm64
    # labels="$labels,pnpm-node16-$arch:docker://yanhao98/pnpm:8-node16"
    # labels="$labels,pnpm-node18-$arch:docker://yanhao98/pnpm:8-node18"
    # labels="$labels,pnpm-node20-$arch:docker://yanhao98/pnpm:8-node20"
    runs-on: pnpm-node${{ matrix.node-version }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - arm64
          - amd64
        node-version:
          - 18
          - 20
    steps:
      - uses: actions/checkout@v4

      - name: pnpm version
        run: pnpm -v

      - name: Install Dependencies
        run: |
          time pnpm install -r --frozen-lockfile --store-dir "$RUNNER_TOOL_CACHE/pnpm-store" --registry=https://registry.npmmirror.com

      - name: Build
        run: time pnpm run -r build

      - name: TestHash
        run: |
          echo "START"
          # https://github.com/nektos/act/issues/1012
          echo "END"
