# [2 Ways to Use Your Own Docker Image in Github Actions](https://yonatankra.com/2-ways-to-use-your-docker-image-in-github-actions/)
# https://github.com/g-plane/pnpm-docker
# https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time

# act --workflows .gitea/workflows/41-pnpm.yml --pull=false

on:
  push:
    branches: ["main"]
    paths:
      - "vite-vue-ts/**"
      - "vite-react-ts/**"
      - ".gitea/workflows/041-pnpm-container-image.yml"
# defaults:
#   run:
#     shell: bash
jobs:
  pnpm:
    # runs-on: pnpm-node20-arm64
    # labels="$labels,pnpm-node16-$arch:docker://yanhao98/pnpm:8-node16"
    # labels="$labels,pnpm-node18-$arch:docker://yanhao98/pnpm:8-node18"
    # labels="$labels,pnpm-node20-$arch:docker://yanhao98/pnpm:8-node20"
    runs-on: pnpm-node${{ matrix.node-version }}-${{ matrix.arch }}
    strategy:
      matrix:
        arch:
          - arm64
          # - amd64
        node-version:
          # - 18
          - 20
    steps:
      - uses: actions/checkout@v4

      - run: pnpm -v

      - name: Set pnpm store
        run: |
          set -x
          echo "RUNNER_TOOL_CACHE: $RUNNER_TOOL_CACHE"
          pnpm store path
          # pnpm config set store-dir "$RUNNER_TOOL_CACHE/pnpm-store"
          pnpm config set registry https://registry.npmmirror.com
          pnpm store path

      - name: Install Dependencies
        run: |
          time pnpm install -r --frozen-lockfile
          # --store-dir "$RUNNER_TOOL_CACHE/pnpm-store" --registry=https://registry.npmmirror.com

      - name: depcheck
        run: |
          set -x
          npx depcheck || true
          node .depcheck.js
        working-directory: vite-vue-ts

      - name: Build
        run: time pnpm run -r build
        env:
          VITE_BUILD_SHA: ${{ github.sha }}

      - name: TestHash
        run: |
          echo "START"
          # https://github.com/nektos/act/issues/1012
          echo "-${{ hashFiles('vite-vue-ts/pnpm-lock.yaml') }}"
          echo "-${{ hashFiles('vite-react-ts/pnpm-lock.yaml') }}"
          echo "-${{ hashFiles('vite-vue-ts/pnpm-lock.yaml', 'vite-react-ts/pnpm-lock.yaml') }}"
          echo "-${{ hashFiles('vite-react-ts/pnpm-lock.yaml', 'vite-vue-ts/pnpm-lock.yaml') }}"
          echo "-${{ hashFiles('**/pnpm-lock.yaml') }}"
          echo "END"
