name: Gitea Actions Demo
run-name: ${{ github.actor }} is testing out Gitea Actions 🚀

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Explore-Gitea-Actions:
  #   runs-on: ubuntu-latest-arm64
  #   steps:
  #     - run: |
  #         echo "🕒 date: $(date)"
  #     - run: curl ip.sb
  #     - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
  #     - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by Gitea!"
  #     - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
  #     - name: Check out repository code
  #       uses: actions/checkout@v4
  #     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
  #     - run: echo "🖥️ The workflow is now ready to test your code on the runner."
  #     - name: List files in the repository
  #       run: ls ${{ github.workspace }}
  #     - run: echo "🍏 This job's status is ${{ job.status }}."

  # Another-Job:
  #   runs-on: ubuntu-latest-arm64
  #   steps:
  #     - run: |
  #         echo "🕒 date: $(date)"
  #     - run: curl ip.sb
  #     - run: env
  #     - run: node -v

  Test-Checkout-1:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /vite-vue-ts/
          sparse-checkout-cone-mode: false
      - run: ls -al
      - run: ls -al vite-vue-ts

  Test-Checkout-2:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            /vite-vue-ts/
          sparse-checkout-cone-mode: true
      - run: ls -al
      - run: ls -al vite-vue-ts
