name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    # paths:
    #   - 'Dockerfile'
    #   - '.github/workflows/docker-image.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    # https://docs.docker.com/build/ci/github-actions/multi-platform/
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    # https://docs.gitea.com/usage/actions/act-runner#labels
    # https://gitea.com/gitea/act_runner/issues/63#issuecomment-745615
    # https://github.com/nektos/act/blob/master/IMAGES.md

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-demo-gitea:latest # https://hub.docker.com/u/murielmay67761
          platforms: linux/amd64,linux/arm64
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: murielmay67761/ci-demo-gitea
