name: Build Vue Project

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: ./vite-vue-ts

jobs:
  only-pnpm:
    # if: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-arm64, ubuntu-amd64]
        node-version:
          # - 18
          - 20
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
          # run_install: true
      - name: Use Node.js ${{ matrix.node-version }}
        run: |
          set -x
          node -v
          pnpm env use ${{ matrix.node-version }} --global
          node -v
          pnpm node -v
          node -v
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Build
        env:
          VITE_BUILD_SHA: ${{ github.sha }}
        run: |
          set -x
          node -v
          pnpm node -v
          pnpm run build
          cat ./dist/index.html | grep data-build-sha
