name: Build Vue Project

on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build-Vue-Project:
    # if: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest-arm64, ubuntu-latest-amd64]
        node-version: [18, 20]
    # defaults:
    #   run:
    #     working-directory: ./vite-vue-ts

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          # run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: "./vite-vue-ts/pnpm-lock.yaml"
      - name: Install dependencies and build
        env:
          VITE_BUILD_SHA: ${{ github.sha }}
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          cat ./dist/index.html
        working-directory: ./vite-vue-ts
      # https://git.yanhao.ren/yanhao/ci-demo/actions/runs/115 左边，制品。
      # - name: Archive Production Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: dist
      #     path: vite-vue-ts/dist

  Build-Vue-Project-Without-Setup-Node:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest-arm64, ubuntu-latest-amd64]
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: true
      - name: Install dependencies and build
        env:
          VITE_BUILD_SHA: ${{ github.sha }}
        run: |
          echo "node version: $(node -v)"
          pnpm env use 18 --global
          echo "node version: $(node -v)"
          pnpm run build
          cat ./dist/index.html
        working-directory: ./vite-vue-ts
