# https://about.gitea.com/resources/tutorials/enable-gitea-actions-cache-to-accelerate-cicd
# https://docs.gitea.com/usage/actions/act-runner#configuring-cache-when-starting-a-runner-using-docker-image
# https://gitea.com/gitea/act_runner
# https://gitea.com/gitea/act_runner/issues/70

# [cache](https://gitea.com/gitea/act_runner/issues/70#issuecomment-734824)
# [cache](https://seepine.com/git/gitea/actions/)

name: Test Cache
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Cache-Java-Test:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 17
      - run: java -version

  pnpm-cache:
    runs-on: ubuntu-latest-arm64
    # defaults:
    #   run:
    #     working-directory: ./vite-vue-ts
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest-arm64, ubuntu-latest-amd64]
    #     node-version: [16, 18, 20]
    steps:
      - run: echo "node version $(node -v)"

      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: ./vite-vue-ts/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --recursive

      - run: echo "node version $(node -v)"
