# https://about.gitea.com/resources/tutorials/enable-gitea-actions-cache-to-accelerate-cicd
# https://docs.gitea.com/usage/actions/act-runner#configuring-cache-when-starting-a-runner-using-docker-image
# https://gitea.com/gitea/act_runner
# https://gitea.com/gitea/act_runner/issues/70

# [cache](https://gitea.com/gitea/act_runner/issues/70#issuecomment-734824)
# [cache](https://seepine.com/git/gitea/actions/)

name: Test Cache
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Cache-Java-Test:
    # container:
    #   image: catthehacker/ubuntu:act-latest
    #   # 方法二，手动指定持久化目录
    #   volumes:
    #     - ubuntu_hostedtoolcache:/opt/hostedtoolcache
    env:
      RUNNER_TOOL_CACHE: /toolcache
    runs-on: ubuntu-latest
    # container:
    #   image: your_docker_image
    #   volumes:
    #     - your_docker_volumn:/opt/hostedtoolcache
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "17"
      - run: java -version
