name: Sync to GitHub

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Push to GitHub
        run: |
          git remote set-url origin https://${{ secrets.GH_TOKEN_YANHAOGITHUB2023 }}@github.com/yanhaogithub2023/ci-demo.git
          git push origin main
