name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    # https://docs.docker.com/build/ci/github-actions/multi-platform/
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          pull: true
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ci-demo-github:latest # https://hub.docker.com/u/murielmay67761
          platforms: linux/amd64,linux/arm64
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: murielmay67761/ci-demo-github
