# act --workflows .github/workflows/41-pnpm-container-image.yml --pull=false

on:
  push:
    branches: ["main"]
  pull_request:
defaults:
  run:
    shell: bash
jobs:
  pnpm-image:
    runs-on: ubuntu-latest
    container:
      # image: yanhao98/pnpm:8-node16
      image: yanhao98/pnpm:8-node${{ matrix.node-version }}
    strategy:
      matrix:
        node-version:
          # - 18
          - 20
    steps:
      - uses: actions/checkout@v4

      - run: pnpm -v

      - name: Set pnpm store
        run: |
          set -x
          pnpm store path
          # pnpm config set store-dir "$RUNNER_TOOL_CACHE/pnpm-store"
          pnpm config set registry https://registry.npmmirror.com
          pnpm store path

      - name: Install Dependencies
        run: |
          time pnpm install -r --frozen-lockfile
      
      - name: depcheck
        run: |
          set -x
          npx depcheck || true
          node .depcheck.js
        working-directory: vite-vue-ts

      - name: Build
        run: |
          time pnpm run -r lint
          time pnpm run -r build
        env:
          VITE_BUILD_SHA: ${{ github.sha }}

      - name: TestHash
        shell: bash
        run: |
          echo "START"
          # https://github.com/nektos/act/issues/1012
          echo "-${{ hashFiles('vite-vue-ts/pnpm-lock.yaml') }}"
          echo "-${{ hashFiles('vite-react-ts/pnpm-lock.yaml') }}"

          echo "-${{ hashFiles('vite-vue-ts/pnpm-lock.yaml', 'vite-react-ts/pnpm-lock.yaml') }}"
          echo "-${{ hashFiles('vite-react-ts/pnpm-lock.yaml', 'vite-vue-ts/pnpm-lock.yaml') }}"

          echo "-${{ hashFiles('**/pnpm-lock.yaml') }}"
          echo "END"
