name: Send Email
on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      send-mail:
        description: "Send mail"
        type: boolean
        default: false

jobs:
  send-mail:
    if: ${{ github.event.inputs.send-mail == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -x
          echo ${{ github.event.inputs.send-mail }}
          echo ${{ github.event.inputs.send-mail == 'true' }}

      - uses: actions/checkout@v4
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          subject: Github Actions job result
          to: obiwan@oo1.dev,yoda@oo1.dev
          from: Luke Skywalker
          # body: Build job of ${{github.repository}} completed successfully!
          attachments: ./*.txt
          priority: high
